language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4'
- '6'
sudo: false
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report
  lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  && rm -rf ./coverage
notifications:
  slack:
    secure: wfab3oO6nIm14U+9z0bbvHIDDcStcE5HWrXqZcchkQnK8tx/1TOpr58t/WobLBkEod5V47500Fe86D3osaa0Y2+1DreKyEcxCbzv/o8IctYIIMgwnJ0naFxNzKmZy79iWNGwAkwwx9HWzxxFBWMJ6UrTH+SdLs4pfmmWFuPmap49LngJ3MwPvAhfbUG8GxzJXU/c9eywr5BSHyYYRMbvxbBn5HWQF3Sd22EpF4DVdu/tC9WiRoiw+xy9h5ZxodpfQ2V35AjXgrLzKo9z/gBVk2+tfpxMIoRuuW1J1HWblSsV8jh5BtZpl4v8iRL8qj4tixCf4ENxpwAohNWDVURUTw4m6zrrvQ4NPAtRZre0D3DKKr+sOD1TBSzT2rZq2ypGkY2luOcmhuFZdt7x6sWHVHM+zeIH2UeqxsHgOHXobwpxEksjkN5UD63hKrC3mFYdTlu0EMStOMFBqfUYe5rypkOXiEQUAyWr6zTBT6uDOXPAQJ/XphhHdXovcAgUAzU3jSHaS5Bw1LGwFJyDmnGxbTrffetQte0jxgCbyvfm/DEBWJOp/W94Foznxu/pXMvMpb6iqqGhcUK701eT5CJJuNKkHvLpuacFa1Vibay/UBrlsPT4wkcuTVfNv7RGhxc13OamANdOwfrL5YLc1BEZxUMcUW0hKuMxZNkTthexlNI=
