language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4'
- '6'
sudo: false
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report
  lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  && rm -rf ./coverage
notifications:
  slack:
    secure: wfab3oO6nIm14U+9z0bbvHIDDcStcE5HWrXqZcchkQnK8tx/1TOpr58t/WobLBkEod5V47500Fe86D3osaa0Y2+1DreKyEcxCbzv/o8IctYIIMgwnJ0naFxNzKmZy79iWNGwAkwwx9HWzxxFBWMJ6UrTH+SdLs4pfmmWFuPmap49LngJ3MwPvAhfbUG8GxzJXU/c9eywr5BSHyYYRMbvxbBn5HWQF3Sd22EpF4DVdu/tC9WiRoiw+xy9h5ZxodpfQ2V35AjXgrLzKo9z/gBVk2+tfpxMIoRuuW1J1HWblSsV8jh5BtZpl4v8iRL8qj4tixCf4ENxpwAohNWDVURUTw4m6zrrvQ4NPAtRZre0D3DKKr+sOD1TBSzT2rZq2ypGkY2luOcmhuFZdt7x6sWHVHM+zeIH2UeqxsHgOHXobwpxEksjkN5UD63hKrC3mFYdTlu0EMStOMFBqfUYe5rypkOXiEQUAyWr6zTBT6uDOXPAQJ/XphhHdXovcAgUAzU3jSHaS5Bw1LGwFJyDmnGxbTrffetQte0jxgCbyvfm/DEBWJOp/W94Foznxu/pXMvMpb6iqqGhcUK701eT5CJJuNKkHvLpuacFa1Vibay/UBrlsPT4wkcuTVfNv7RGhxc13OamANdOwfrL5YLc1BEZxUMcUW0hKuMxZNkTthexlNI=
deploy:
  provider: npm
  email: support@hypertrack.io
  api_key:
    secure: zP1XmNMLi6qS6bRHpM7sek9xt6yHoECa/2HTM6izi7K2ixEC1tL6/8haR2Mcc8hmZD76+UgLuw64GsQFZiJ85C/8sw3YhOC7VWGzHY7LqlIbQ+t00RcmKerf4oGBi+2QLTho9NmhybfcJe/syE0m7hdqd+hb5QvCoQQ2FrVAne1PVgeOINZVMSav+myZCA3s9dhpb+WuoePrJ6e3BMdvkFVOIGyH1KvT2fzmfhQRpmzG9+MynDhguZWb9bsm8pA4bweNa/avu1ya26iRhHhkCPLyPejMOh2me7kDi/NzQYGQYlTSKsS0Y5WhcYYP+ii7h4kQ0AyPmo3gM4f8RZKFBNCI3VGn5Mv/pKw/505W8sbFYbCZl69FBYPctq1Ms5hfhdksdLeSMmpiYKUd251qXNo7RsSqpGVCRJyoRcCaGFQQLjxvRAMXg8OKIsa5yqiF3cByayC/AlEpseemw7rTK3heeE6xl0HqOkGFvW6lPFl2kNSjwfazNyWSBAyh4AUPVtf0mM9luPfsMe/r/W1OSjv6KiBrmF+SNsb3s6AevV/+wOymCuROUCuFvm5dFKgMF4FVgArc2I/tsKmoQyN8f1v132wGYEY+ZRh7fL5Q+vMIyWLPVl/6cV7Qjq+9yvWxC2PJHplH0HQ+Z++n5tBwDYtNclU24T7Lc264B0Yej+c=
  on:
    branch: master
    repo: hypertrack/hypertrack-node
